### ISSUE TITLE
Cannot read property 'handshaken'.

### ISSUE THREAD

**Issue by Sergio3** [tykeal/ep_ldapauth#24]
Hi!

I Installed the last Etherpad-lite and ep_ldapauth version on a Debian server and after login through LDAP with no problem, I cannot access to the pads. Every pad shows the next error:

---------------------------------------------------------------------------------------------------------------------
An error occured
The error was reported with the following id: 'xhpbmxFHRbJIMzD9N4JH'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: xhpbmxFHRbJIMzD9N4JH
URL: http://everest.uab.cat:55001/p/prueba
UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0
TypeError: pad.collabClient is null in http://xxxxx.xxx.xxx:55112/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 266'
-----------------------------------------------------------------------------------------------------------------------

And here's the error displayed on Debian console:

[2015-05-11 14:04:13.880] [ERROR] console - TypeError: Cannot read property 'handshaken' of undefined
    at Object.exports.handleMessage [as hook_fn] (/var/www/etherpad-lite/node_modules/ep_ldapauth/ep_ldapauth.js:176:43)
    at normalizedhook (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:88:7
    at /var/www/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at /var/www/etherpad-lite/src/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/var/www/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
    at async.each (/var/www/etherpad-lite/src/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/var/www/etherpad-lite/src/node_modules/async/lib/async.js:248:13)

Any help would be appreciated.

Thank you!

**Comment by kadogo** [comment]
I had the same problem.
But I replace ep_ldapauth.js  by this https://github.com/tykeal/ep_ldapauth/blob/master/ep_ldapauth.js

And now it work without troubles.
