### ISSUE TITLE
Property Anonymous Read Only

### ISSUE THREAD

**Issue by bashinate-git** [tykeal/ep_ldapauth#38]
TypeError: Cannot read property 'anonymousReadonly' of undefined

```
"users": {
    "ldapauth": {
        "url": "ldap://domain.local:389",
        "accountBase": "ou=People,dc=domain,dc=local",
        "accountPattern": "(&(objectClass=*)(uid={{username}}))",
        "displayNameAttribute": "cn",
        "searchDN": "CN=etherpad-ldap,OU=ServiceAccounts,OU=People,DC=domain,DC=local",
        "searchPWD": "caaccacacaca",
        "groupSearchBase": "ou=People,dc=domain,dc=local",
        "groupAttribute": "member",
        "groupAttributeIsDN": true,
        "searchScope": "sub",
        "groupSearch": "(&(cn=admin)(objectClass=Important People))",
        "anonymousReadonly": false
    }
},
```

the json is proper for anonymousReadonly as it is the last item in the dictionary and therefore doesnt need a comma. Doesnt make sense why its throwing the error. Any ideas?

Thanks

**Comment by tykeal** [comment]
I don't see any issues with your configuration either, though (objectClass=Important People) seems a bit odd to me, I can only assume your LDAP scheme has some extended class named that.

**Comment by bashinate-git** [comment]
I commented out the anonymousReadonly function and am now getting an undefined url error however I am using a valid ldap url. 

`[2018-03-02 12:54:13.038] [ERROR] console - TypeError: Cannot read property 'url' of undefined
    at Object.exports.authenticate [as hook_fn] (/etherpad/etherpad-lite/node_modules/ep_ldapauth/ep_ldapauth.js:36:35)
    at normalizedhook (/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:111:7
    at next (/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:46:5)
    at Object.exports.mapFirst (/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:52:3)
    at Object.exports.aCallFirst (/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:108:11)
    at authenticate (/etherpad/etherpad-lite/src/node/hooks/express/webaccess.js:45:20)
    at /etherpad/etherpad-lite/src/node/hooks/express/webaccess.js:83:5
    at /etherpad/etherpad-lite/src/node/hooks/express/webaccess.js:15:14
`

**Comment by bashinate-git** [comment]
I have pointed it to one DC and it is not even querying. I am getting an http 500 error.
When looking at AD logs no query even shows up. 

```
[2018-03-02 14:16:39.689] [DEBUG] ueberDB - SET    - sessionstorage:sbgceszr0uG5UjCrZ8wrwqt4jEVh7f4O - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true,"secure":false}} - to database
[2018-03-02 14:16:39.693] [DEBUG] http - 500, GET /
```

**Comment by erebane** [comment]
I had this issue when building latest from master, it disappeared when I built it with release version 1.7.5.

**Comment by DerTim1** [comment]
Adding `"password": "dummy_password"` to ldapauth-seciton in settings.json solved the problem for my setup.
