### ISSUE TITLE
Seems to be broken with with etherpad version 1.8.13

### ISSUE THREAD

**Issue by smhaller** [tykeal/ep_ldapauth#50]
With etherpad version 1.8.12 it is working. Updating to 1.8.13 yields to
```
[2021-04-22 13:28:24.933] [INFO] plugins - npm --version: 6.14.11
[2021-04-22 13:28:28.029] [ERROR] runCmd|npm - npm ERR! extraneous: ep_etherpad-lite@1.8.11 /home/c7031016/etherpad-lite/node_modules/ep_etherpad-lite
[2021-04-22 13:28:28.047] [DEBUG] runCmd - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
    at exports (/home/c7031016/etherpad-lite/src/node/utils/run_cmd.js:119:25)
    at Object.exports.getPackages (/home/c7031016/etherpad-lite/src/static/js/pluginfw/plugins.js:93:48)
    at Object.exports.update (/home/c7031016/etherpad-lite/src/static/js/pluginfw/plugins.js:67:34)
    at Object.exports.start (/home/c7031016/etherpad-lite/src/node/server.js:140:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-04-22 13:28:28.047] [ERROR] server - Error occurred while starting Etherpad
[2021-04-22 13:28:28.048] [ERROR] server - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
    at exports (/home/c7031016/etherpad-lite/src/node/utils/run_cmd.js:119:25)
    at Object.exports.getPackages (/home/c7031016/etherpad-lite/src/static/js/pluginfw/plugins.js:93:48)
    at Object.exports.update (/home/c7031016/etherpad-lite/src/static/js/pluginfw/plugins.js:67:34)
    at Object.exports.start (/home/c7031016/etherpad-lite/src/node/server.js:140:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-04-22 13:28:28.049] [INFO] server - Exiting...
[2021-04-22 13:28:28.049] [INFO] server - Waiting for Node.js to exit...
```

Without the plugin etherpad is running.

**Comment by pcworld** [comment]
The plugin works for me on 1.8.16. The stack trace you posted does not appear to originate from ep_ldapauth code.
